### ISSUE TITLE
Wrong with pytorch=0.4.1

### ISSUE THREAD

**Issue by DogeWatch** [Hanjun-Dai/pytorch_structure2vec#16]
Traceback (most recent call last):
  File "main.py", line 124, in <module>
    test_loss = loop_dataset(test_data, regressor, list(range(len(test_data))))
  File "main.py", line 56, in loop_dataset
    _, mae, mse = regressor(batch_graph)
  File "/home/worker/anaconda3/envs/struc2vec/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "main.py", line 101, in forward
    embed = self.s2v(batch_graph, node_feat, edge_feat)
  File "/home/worker/anaconda3/envs/struc2vec/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/worker/dodge/project/pytorch_structure2vec/harvard_cep/../s2v_lib/embedding.py", line 50, in forward
    h = self.mean_field(node_feat, edge_feat, n2n_sp, e2n_sp, subg_sp)
  File "/home/worker/dodge/project/pytorch_structure2vec/harvard_cep/../s2v_lib/embedding.py", line 59, in mean_field
    e2npool_input = gnn_spmm(e2n_sp, input_edge_linear)
  File "/home/worker/dodge/project/pytorch_structure2vec/harvard_cep/../s2v_lib/pytorch_util.py", line 70, in gnn_spmm
    return MySpMM.apply(sp_mat, dense_mat)
  File "/home/worker/dodge/project/pytorch_structure2vec/harvard_cep/../s2v_lib/pytorch_util.py", line 56, in forward
    return torch.mm(sp_mat, dense_mat)
RuntimeError: addmm: expected 'mat1' to be CUDA, but got CPU

**Comment by Hanjun-Dai** [comment]
fixed! please pull the latest version.
