### ISSUE TITLE
error message when running python mol_lib.py

### ISSUE THREAD

**Issue by hjhung** [Hanjun-Dai/pytorch_structure2vec#18]
When I run 

```
cd harvard_cep
python mol_lib.py
```

I got the following error:

> Traceback (most recent call last):
>   File "mol_lib.py", line 115, in <module>
>     MOLLIB = _mol_lib()
>   File "mol_lib.py", line 12, in __init__
>     self.lib = ctypes.CDLL('%s/build/dll/libmol.so' % dir_path)
>   File "/home/account/anaconda3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: /home/account/pytorch_structure2vec-master/harvard_cep/build/dll/libmol.so: undefined symbol: _ZN5RDKit17SmilesMolSupplierC1ERKSsS2_iibb

I think this issue is related with #2, but I can not solve this problem with the suggestion.  I have tried to rebuilt rdkit and boost severl times, but the same error still incurs. 

Thanks for help!

**Comment by Hanjun-Dai** [comment]
Hi,

Have you properly defined the LD_LIBRARY_PATH to include your rdkit lib?

**Comment by hjhung** [comment]
Hi, 

Yes, I set LD_LIBRARY_PATH as /home/account/boost/lib/:/home/account/rdkit/lib. Did I missing something needed?

**Comment by hjhung** [comment]
Hi,

Yes, I did make install but still got the error. 

I was wondering whether this is because of the boost library. I can not install the boost.python successfully in my home directory (1.65.1) successfully and thus another version of boost (in /usr/include/boost, 1.69.0) is also used in the process.  

Thanks!

**Comment by Hanjun-Dai** [comment]
which version of rdkit are you using?

**Comment by hjhung** [comment]
I am using Release_2019.03.1.

**Comment by Hanjun-Dai** [comment]
can you try Release_2017_09_2? that was the version I've tested. 

I'll also try with new versions of rdkit later

**Comment by hjhung** [comment]
Of course, will try and let you know later. Thanks a lot!

**Comment by Hanjun-Dai** [comment]
It seems you don't have c++ boost installed?

**Comment by hjhung** [comment]
I installed boost 1.65.1.  With the same environment and the latest rdkit, I could install rdkit successfully but could not run mol_lib.py as mentioned in the top of this issue.

**Comment by Hanjun-Dai** [comment]
you need to make sure you have included boost libs in LD_LIBRARY_PATH

**Comment by hjhung** [comment]
Yes, I have included the boost libs in LD_LIBRARY_PATH.

```
$ echo $LD_LIBRARY_PATH
/home/account/boost/lib/:/home/account/rdkit/lib:/usr/lib64
```
