### ISSUE TITLE
error message when running make -j4

### ISSUE THREAD

**Issue by xuzhang5788** [Hanjun-Dai/pytorch_structure2vec#8]
After I ran these
cd harvard_cep
make -j4
I received 

g++ -Wall -O3 -std=c++11 -I./include -I/home/xuzhang/anaconda3/envs/rdkit/Code -Wno-unused-local-typedef -fPIC -MMD -c -o build/lib/mol_utils.o src/lib/mol_utils.cpp
In file included from src/lib/mol_utils.cpp:1:0:
./include/mol_utils.h:5:31: fatal error: GraphMol/RingInfo.h: No such file or directory
compilation terminated.
Makefile:41: recipe for target 'build/lib/mol_utils.o' failed
make: *** [build/lib/mol_utils.o] Error 1

Your help is highly appreciated

**Comment by ManSoSec** [comment]
I installed rdkit by "https://github.com/rdkit/homebrew-rdkit" on my Ma, but got the same error.
I solved it by cloning the rdkit source code, compiling it, and passing its path to RDBASE instead of the installed path.

**Comment by xuzhang5788** [comment]
Thank you @ManSoSec & @Hanjun-Dai 

I am using Ubuntu and I installed rdkit by anaconda. If I reinstall rdkit through source code, I don't know if my other codes using rdkit will not work. By the way, I don't understand what I should do when you say compiling it @ManSoSec

**Comment by ManSoSec** [comment]
Download rdkit source code: https://github.com/rdkit/rdkit
unzip rdkit-master.zip
cd rdkit-master
cmake .
make -j4
Then use 'rdkit-master' path for RDBASE.

**Comment by xuzhang5788** [comment]
Thank you @ManSoSec very much.

I followed your instruction, but after I run make -j4, I got 

[ 80%] Building CXX object Code/GraphMol/Descriptors/CMakeFiles/Descriptors_static.dir/WHIM.cpp.o
[ 80%] Linking CXX shared library ../../../lib/libRDKitDescriptors.so
[ 80%] Built target Descriptors
[ 80%] Linking CXX static library libRDKitDescriptors_static.a
[ 80%] Built target Descriptors_static
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

If I ignore those things and directly run
python main.py -gm loopy_bp -saved_model saved/loopy_bp.model -phase test

I got
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from mol_lib import MOLLIB, MolGraph
  File "/media/projects/pytorch_structure2vec/harvard_cep/mol_lib.py", line 115, in <module>
    MOLLIB = _mol_lib()
  File "/media/projects/pytorch_structure2vec/harvard_cep/mol_lib.py", line 12, in __init__
    self.lib = ctypes.CDLL('%s/build/dll/libmol.so' % dir_path)
  File "/home/xuzhang/anaconda3/lib/python3.5/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /media/projects/pytorch_structure2vec/harvard_cep/build/dll/libmol.so: undefined symbol: _ZN5RDKit17SmilesMolSupplierC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_iibb

Any ideas? Many thanks

**Comment by Hanjun-Dai** [comment]
can you provide more information about the compilation error?

**Comment by xuzhang5788** [comment]
@Hanjun-Dai 
I follow @ManSoSec 's procedure like this
Download rdkit source code: https://github.com/rdkit/rdkit
unzip rdkit-master.zip
cd rdkit-master
cmake .
make -j4

I just redo it and I got the followings:
[  0%] Built target coordgen_support
[  0%] Built target inchi_support
[  1%] Built target maeparser_static
[  1%] Built target maeparser
[  2%] Built target RDGeneral
[  3%] Built target RDGeneral_static
[  3%] Built target hc
[  4%] Built target hc_static
[  5%] Built target coordgenlib
[  7%] Built target coordgenlib_static
[  7%] Built target EigenSolvers
[  7%] Built target RDBoost
[  8%] Built target DataStructs
[  8%] Built target testDict
[  8%] Built target testRDValue
[  9%] Built target testFPB
[ 10%] Built target RDBoost_static
[ 10%] Built target testMultiFPB
[ 11%] Built target testDataStructs
[ 11%] Built target testMatrices
[ 11%] Built target rdBase
[ 12%] Built target DataStructs_static
[ 13%] Built target cDataStructs
[ 13%] Built target EigenSolvers_static
[ 13%] Built target testQuery
[ 13%] Built target testMatCalc
[ 14%] Built target Catalogs_static
[ 14%] Built target Catalogs
[ 14%] Built target SimDivPickers
[ 15%] Built target rdMetricMatrixCalc
[ 15%] Built target SimDivPickers_static
[ 15%] Built target Clustering
[ 15%] Built target InfoTheory_static
[ 15%] Built target testSimDivPickers
[ 15%] Built target RDGeometryLib
[ 15%] Built target rdSimDivPickers
[ 16%] Built target RDGeometryLib_static
[ 16%] Built target Alignment
[ 17%] Built target testGrid
[ 17%] Built target InfoTheory
[ 18%] Built target testTransforms
[ 18%] Built target Alignment_static
[ 18%] Built target testAlignment
[ 18%] Built target rdAlignment
[ 18%] Built target rdInfoTheory
[ 19%] Built target cQuantize
[ 19%] Built target ChemicalFeatures
[ 20%] Built target ChemicalFeatures_static
[ 20%] Built target testChemicalFeatures
[ 21%] Built target rdGeometry
[ 25%] Built target GraphMol_static
[ 28%] Built target GraphMol
[ 28%] Built target Trajectory_static
[ 28%] Built target SubstructMatch_static
[ 29%] Built target Subgraphs
[ 29%] Built target Subgraphs_static
[ 30%] Built target SmilesParse_static
[ 30%] Built target MolTransforms_static
[ 30%] Built target MolCatalog_static
[ 30%] Built target PartialCharges
[ 30%] Built target PartialCharges_static
[ 31%] Built target MolCatalog
[ 31%] Built target ReducedGraphs_static
[ 32%] Built target SLNParse_static
[ 32%] Built target MolInterchange_static
[ 32%] Built target MolInterchange
[ 32%] Built target SLNParse
[ 33%] Built target rdChemicalFeatures
[ 33%] Built target rdqueries
[ 34%] Built target MolTransforms
[ 35%] Built target SubstructMatch
[ 35%] Built target Trajectory
[ 36%] Built target Optimizer_static
[ 38%] Built target SmilesParse
[ 38%] Built target ChemTransforms_static
[ 39%] Built target testPartialCharges
[ 40%] Built target Fingerprints_static
[ 41%] Built target FilterCatalog_static
[ 41%] Built target rdPartialCharges
[ 42%] Built target FragCatalog_static
[ 43%] Built target rdMolTransforms
[ 43%] Built target ShapeHelpers
[ 43%] Built target MolChemicalFeatures
[ 44%] Built target MolChemicalFeatures_static
[ 45%] Built target ShapeHelpers_static
[ 45%] Built target rdMolInterchange
[ 46%] Built target ReducedGraphs
[ 46%] Built target SubstructLibrary_static
[ 47%] Built target rdSLNParse
[ 48%] Built target testSLNParse
[ 48%] Built target Optimizer
[ 48%] Built target rdtrajectory
[ 48%] Built target graphmoltestCanon
[ 48%] Built target graphmolIterTest
[ 48%] Built target graphmolqueryTest
[ 49%] Built target test-valgrind
[ 50%] Built target graphmolcpTest
[ 50%] Built target graphmolMemTest1
[ 50%] Built target smaTest1
[ 51%] Built target ChemTransforms
[ 52%] Built target FilterCatalog
[ 53%] Built target testSubgraphs1
[ 53%] Built target testSubgraphs2
[ 53%] Built target Fingerprints
[ 56%] Built target ForceField_static
[ 56%] Built target rdShapeHelpers
[ 56%] Built target rdReducedGraphs
[ 56%] Built target SubstructLibrary
[ 57%] Built target rdMolChemicalFeatures
[ 57%] Built target testReducedGraphs
[ 57%] Built target FragCatalog
[ 57%] Built target testOptimizer
[ 58%] Built target ForceFieldHelpers_static
[ 59%] Built target rdchem
[ 59%] Built target MolAlign_static
[ 62%] Built target ForceField
[ 63%] Built target DistGeometry_static
[ 63%] Built target ForceFieldHelpers
[ 63%] Built target Depictor_static
[ 64%] Built target DistGeomHelpers_static
[ 64%] Built target rdForceField
[ 65%] Built target MolAlign
[ 65%] Built target DistGeometry
[ 65%] Built target rdForceFieldHelpers
[ 65%] Built target rdCoordGen
[ 66%] Built target Depictor
[ 66%] Built target testDistGeom
[ 66%] Built target DistGeomHelpers
[ 66%] Built target DistGeom
[ 68%] Built target FileParsers_static
Scanning dependencies of target FMCS_static
Scanning dependencies of target MMPA_static
[ 70%] Built target FileParsers
[ 70%] Built target testCoordGen
[ 70%] Built target testUFFForceField
[ 70%] Built target testMMFFForceField
[ 73%] Built target Descriptors_static
[ 73%] Built target graphmoltestChirality
[ 73%] Built target molBundleTest
[ 74%] Built target graphmoltestPickler
[ 74%] Built target graphmolMolOpsTest
[ 74%] Built target hanoiTest
[ 74%] Built target graphmoltestPicklerGlobalSetting
[ 75%] Built target resMolSupplierTest
[ 75%] Building CXX object Code/GraphMol/MMPA/CMakeFiles/MMPA_static.dir/MMPA.cpp.o
[ 75%] Built target graphmolTest1
[ 75%] Built target testDepictor
[ 75%] Built target rdDepictor
[ 75%] Built target cxsmilesTest
[ 75%] Building CXX object Code/GraphMol/FMCS/CMakeFiles/FMCS_static.dir/FMCS.cpp.o
[ 75%] Built target smiTest1
[ 75%] Building CXX object Code/GraphMol/FMCS/CMakeFiles/FMCS_static.dir/Seed.cpp.o
[ 75%] Built target fileParsersTest1
[ 75%] Built target testTplParser
[ 75%] Building CXX object Code/GraphMol/FMCS/CMakeFiles/FMCS_static.dir/MaximumCommonSubgraph.cpp.o
[ 75%] Building CXX object Code/GraphMol/FMCS/CMakeFiles/FMCS_static.dir/SubstructMatchCustom.cpp.o
[ 75%] Linking CXX static library libRDKitMMPA_static.a
[ 75%] Built target MMPA_static
[ 75%] Built target testMol2ToMol
[ 76%] Built target testMolWriter
[ 76%] Built target testMolSupplier
[ 76%] Built target testSequence
[ 76%] Built target testSubstructMatch
Scanning dependencies of target ChemReactions_static
[ 78%] Built target Descriptors
[ 79%] Built target testChemTransforms
[ 80%] Linking CXX executable filterCatalogTest
../../../lib/libRDKitFilterCatalog.so.1.2018.09.1dev1: undefined reference to `boost::archive::text_iarchive_impl<boost::archive::text_iarchive>::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
../../../lib/libRDKitFilterCatalog.so.1.2018.09.1dev1: undefined reference to `boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::save(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
Code/GraphMol/FilterCatalog/CMakeFiles/filterCatalogTest.dir/build.make:116: recipe for target 'Code/GraphMol/FilterCatalog/filterCatalogTest' failed
make[2]: *** [Code/GraphMol/FilterCatalog/filterCatalogTest] Error 1
CMakeFiles/Makefile2:5415: recipe for target 'Code/GraphMol/FilterCatalog/CMakeFiles/filterCatalogTest.dir/all' failed
make[1]: *** [Code/GraphMol/FilterCatalog/CMakeFiles/filterCatalogTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 80%] Building CXX object Code/GraphMol/ChemReactions/CMakeFiles/ChemReactions_static.dir/Reaction.cpp.o
[ 80%] Building CXX object Code/GraphMol/ChemReactions/CMakeFiles/ChemReactions_static.dir/MDLParser.cpp.o
[ 80%] Building CXX object Code/GraphMol/ChemReactions/CMakeFiles/ChemReactions_static.dir/DaylightParser.cpp.o
[ 80%] Linking CXX static library libRDKitFMCS_static.a
[ 80%] Built target FMCS_static
[ 80%] Building CXX object Code/GraphMol/ChemReactions/CMakeFiles/ChemReactions_static.dir/ReactionPickler.cpp.o
[ 80%] Building CXX object Code/GraphMol/ChemReactions/CMakeFiles/ChemReactions_static.dir/ReactionWriter.cpp.o
[ 80%] Building CXX object Code/GraphMol/ChemReactions/CMakeFiles/ChemReactions_static.dir/ReactionDepict.cpp.o
[ 80%] Building CXX object Code/GraphMol/ChemReactions/CMakeFiles/ChemReactions_static.dir/ReactionFingerprints.cpp.o
[ 81%] Building CXX object Code/GraphMol/ChemReactions/CMakeFiles/ChemReactions_static.dir/ReactionUtils.cpp.o
[ 81%] Building CXX object Code/GraphMol/ChemReactions/CMakeFiles/ChemReactions_static.dir/MoleculeParser.cpp.o
[ 81%] Building CXX object Code/GraphMol/ChemReactions/CMakeFiles/ChemReactions_static.dir/ReactionRunner.cpp.o
[ 81%] Building CXX object Code/GraphMol/ChemReactions/CMakeFiles/ChemReactions_static.dir/PreprocessRxn.cpp.o
[ 81%] Building CXX object Code/GraphMol/ChemReactions/CMakeFiles/ChemReactions_static.dir/SanitizeRxn.cpp.o
[ 81%] Building CXX object Code/GraphMol/ChemReactions/CMakeFiles/ChemReactions_static.dir/Enumerate/Enumerate.cpp.o
[ 81%] Building CXX object Code/GraphMol/ChemReactions/CMakeFiles/ChemReactions_static.dir/Enumerate/EnumerationPickler.cpp.o
[ 81%] Building CXX object Code/GraphMol/ChemReactions/CMakeFiles/ChemReactions_static.dir/Enumerate/EvenSamplePairs.cpp.o
[ 81%] Linking CXX static library libRDKitChemReactions_static.a
[ 81%] Built target ChemReactions_static
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Hanjun-Dai** [comment]
It seems you didn't have boost c++ installed?

**Comment by xuzhang5788** [comment]
@Hanjun-Dai 
When I reinstall boost using $ sudo apt-get install libboost-all-dev, I got 

Reading package lists... Done
Building dependency tree       
Reading state information... Done
libboost-all-dev is already the newest version (1.58.0.1ubuntu1).
The following packages were automatically installed and are no longer required:
  linux-headers-4.13.0-38 linux-headers-4.13.0-38-generic
  linux-headers-4.13.0-39 linux-headers-4.13.0-39-generic
  linux-headers-4.13.0-41 linux-headers-4.13.0-41-generic
  linux-image-4.13.0-38-generic linux-image-4.13.0-39-generic
  linux-image-4.13.0-41-generic linux-image-extra-4.13.0-38-generic
  linux-image-extra-4.13.0-39-generic linux-image-extra-4.13.0-41-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
